### ISSUE TITLE
Avoid mutating React API

### ISSUE THREAD

**Issue by gaearon** [Aweary/react-is-deprecated#1]
Generally monkeypatching third-party API is not a very good idea especially if this out of user’s control. If a component distributed on npm uses this library, end user has no way of opting out of monkeypatching. What if different components rely on different versions of `react-is-deprecated` and include different monkeypatching code?

I would advise to change the API to simple function like `deprecated(PropTypes.string, 'message')`. If you insist on keeping the “fluent” API a better idea would be to return a _copy_ of `PropTypes` with the injected property instead of mutating `React.PropTypes`. But to be honest this seems more counter-intuitive than just providing a function.

**Comment by aweary** [comment]
@gaearon thanks for taking the time to open this issue, I very much appreciate any input. I wrote this very quickly in response to that issue and I agree that it's not the best approach. I think a `deprecate` function would be a better API, and it's what I initially started with, but I figured more people would want it to be consistent with `isRequired`.

What do you think about exporting two functions:
- `deprecate` which wraps the `propType` like `isDeprecated` already does. That gives you the API you mentioned:
  `deprecate(PropTypes.string, 'message')`
- `addIsDeprecated` which returns a _copy_ of the passed `React.PropTypes` and adds the `isDeprecated` method to all propType options.

**Comment by aweary** [comment]
@gaearon https://github.com/Aweary/react-is-deprecated/pull/3 should address the mutation issue. It also exports two functions as described above, recommending `deprecate` in the docs but provided `addIsDeprecated` for those who want it.

I'd love to get any more feedback you have on it before I merge :tada:
